# Generated by Django 5.1.1 on 2024-10-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
