# Generated by Django 5.1.1 on 2024-10-31 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherattendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Attendance', models.CharField(max_length=20)),
                ('teacher_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
